name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.githubactions }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Display Before
      run: ls
    - name: Automated Github Action Maven Version Bump
      id: bump
      uses: mickem/gh-action-bump-maven-version@v1.0.0
    - name: Deploy
      run: mvn compile
    - name: Display Hello-World
      run: java -cp target/classes com.myapp.App
    - name: Package
      run: |
        mvn package
        java -cp "target/myapp-${{env.targetVersion}}.jar" com.myapp.App
      
