name: Java CI with Maven
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.githubactions }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Display Before
      run: ls
    - name: Automated Github Action Maven Version Bump
      id: bump
      uses: mickem/gh-action-bump-maven-version@v1.0.0
    - name: Project Version check (Maven, NodeJS...)
      uses: avides/actions-project-version-check@v1.3.0
      id: myversion
      with:
        token: ${{ secrets.githubactions }}
        file-to-check: pom.xml
        only-return-version: true
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Display Hello-World
      run: java -cp target/classes com.myapp.App
    - name: Display After
      run: tree
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: 4upa4el/my-docker
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: "hello-world-${{ steps.myversion.outputs.version }}"
  run:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.githubactions }}
    - name: Project Version check (Maven, NodeJS...)
      uses: avides/actions-project-version-check@v1.3.0
      id: myversion
      with:
        token: ${{ secrets.githubactions }}
        file-to-check: pom.xml
        only-return-version: true
    - name: Run container
      run: |
        docker run '4upa4el/my-docker:hello-world-${{steps.myversion.outputs.version}}'
